from enum import Enum


class State(Enum):
    # Connection states:
    WAITING_FOR_NETWORK = "WAITING_FOR_NETWORK"
    DISCONNECTED = "DISCONNECTED"
    RECONNECTING = "RECONNECTING"

    CONNECTING = "CONNECTING"
    CONNECTED_KNOWN = "CONNECTED_KNOWN"
    CONNECTED_HOME = "CONNECTED_HOME"
    CONNECTED_NEW = "CONNECTED_NEW"
    CONNECTED_BLACKLISTED = "CONNECTED_BLACKLISTED"

    #Scanning states:
    SCANNING_IN_PROGRESS = "SCANNING_IN_PROGRESS"
    SCAN_COMPLETED = "SCAN_COMPLETED"

    ALERTING = "ALERTING"
